FROM alpine:latest

RUN apk update && \
    apk add --no-cache \
    ansible \
    openssh-client \
    sudo \
    shadow \
    bash \
    nano

RUN useradd -m -s /bin/bash -u 1000 ansible && \
    echo 'ansible ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    mkdir -p /home/ansible/.ssh && \
    chown -R ansible:ansible /home/ansible/.ssh && \
    chmod 700 /home/ansible/.ssh
USER ansible
WORKDIR /home/ansible

CMD ["sleep", "infinity"]
