services:
  controller:
    build:
      context: .
      dockerfile: Dockerfile.controller
    container_name: ansible-controller
    hostname: controller
    volumes:
      - ./ansible:/home/ansible/workdir
    networks:
      ansible-net:
        ipv4_address: 172.18.0.100
    restart: always
    stdin_open: true
    tty: true

  target1: &target-defaults
    build:
      context: .
      dockerfile: Dockerfile.target
    container_name: ansible-target1
    hostname: target1
    networks:
      ansible-net:
        ipv4_address: 172.18.0.3
    restart: always

  target2:
    <<: *target-defaults
    container_name: ansible-target2
    hostname: target2
    networks:
      ansible-net:
        ipv4_address: 172.18.0.4

  target3:
    <<: *target-defaults
    container_name: ansible-target3
    hostname: target3
    networks:
      ansible-net:
        ipv4_address: 172.18.0.8

  target4:
    <<: *target-defaults
    container_name: ansible-target4
    hostname: target4
    networks:
      ansible-net:
        ipv4_address: 172.18.0.6

  target5:
    <<: *target-defaults
    container_name: ansible-target5
    hostname: target5
    networks:
      ansible-net:
        ipv4_address: 172.18.0.2

  target6:
    <<: *target-defaults
    container_name: ansible-target6
    hostname: target6
    networks:
      ansible-net:
        ipv4_address: 172.18.0.9

  target7:
    <<: *target-defaults
    container_name: ansible-target7
    hostname: target7
    networks:
      ansible-net:
        ipv4_address: 172.18.0.12

  target8:
    <<: *target-defaults
    container_name: ansible-target8
    hostname: target8
    networks:
      ansible-net:
        ipv4_address: 172.18.0.5

  target9:
    <<: *target-defaults
    container_name: ansible-target9
    hostname: target9
    networks:
      ansible-net:
        ipv4_address: 172.18.0.7

  target10:
    <<: *target-defaults
    container_name: ansible-target10
    hostname: target10
    networks:
      ansible-net:
        ipv4_address: 172.18.0.11

networks:
  ansible-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
