---
- name: play for set the permission to  recursively 
  hosts: all
  become: yes 
  tasks:
  
    - name: recursively change ownership of a directory 
      ansible.builtin.file: 
        path: /tmp/yaksh
        state: directory 
        recurse: yes 
        owner: ansible
        group: ansible 
 
